name: xlo
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  google_fonts: ^1.1.0
  parse_server_sdk_flutter: ^2.0.0
  font_awesome_flutter: ^8.8.1
  mobx: ^1.2.1+3
  flutter_mobx: ^1.1.0+2
  get_it: ^5.0.1
  brasil_fields: ^0.4.0
  image_picker: 0.6.7+12
  image_cropper: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.10.11
  mobx_codegen: ^1.1.1+1

flutter:

  uses-material-design: true

  assets:
    - assets/images/